language: rust
os:
  - linux
rust: stable
cache:
  directories:
    - "$HOME/.cargo/registry"
    - target
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl https://pre-commit.com/install-local.py | python -
  - rustup component add rustfmt
script:
  - rustfmt --version
  - pre-commit run --all-files
  - cargo test
