[package]
name = "wpm"
version = "0.1.0"
authors = ["William Roe <git@wjlr.org.uk>"]
edition = "2018"
license = "MIT"

[dependencies]
gfx = "0.18"
gfx_device_gl = "0.16"
gfx_window_glutin = "0.30"
glutin = { version = "0.20.0", features = ["serde", "icon_loading"] }
cgmath = "0.17.0"
gfx_glyph = "0.14"
lazy_static = "1.3"
rmp = "0.8"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.5", features = [
  "winbase",
  "consoleapi",
  "shellapi",
  "processenv",
  "synchapi"
] }
